library(ggplot2)
library(gridExtra)

source("examples/ode_models.R")

# =============================================================================
# inspect_data — visualise synthetic data generated by a canonical ODE config
#
# Takes an ODE_CONFIGS entry, runs a forward simulation with the true
# parameters, adds observation noise, and plots the result.  Use this to
# verify that a configuration produces sensible trajectories and appropriate
# noise levels before running any solver.
#
# Arguments
# ---------
# cfg          ODE_CONFIGS entry from examples/ode_models.R.
# noise_sd     Std. dev. of additive Gaussian noise.
#              NULL = auto: 2 % of peak signal amplitude (same as run_example
#              in ode_params_examples.R).
# seed         Random seed for reproducibility.
# show_params  Print the parameter values used to generate the data.
#
# Plots (one per state variable)
# -------------------------------
# Dashed grey  — clean simulated trajectory on cfg$times_sim
# Solid blue   — clean trajectory sampled at cfg$times_obs (no noise)
# Red dots     — noisy observations at cfg$times_obs
# Two vertical bands mark the observation window boundaries.
#
# Returns invisibly: list(y_sim, y_obs_clean, obs_data)
# =============================================================================
inspect_data <- function(cfg,
                         noise_sd    = NULL,
                         seed        = 123,
                         show_params = TRUE) {
  rhs    <- cfg$rhs
  params <- cfg$params
  y0     <- cfg$y0
  t_obs  <- cfg$times_obs
  t_sim  <- cfg$times_sim
  n_vars <- length(y0)
  var_names <- if (!is.null(names(y0))) names(y0) else
    paste0("Var", seq_len(n_vars))

  # Identify which entries of t_sim correspond to t_obs
  obs_idx <- match(round(t_obs, 10), round(t_sim, 10))
  if (anyNA(obs_idx))
    stop("cfg$times_obs contains times not present in cfg$times_sim.")

  # Forward simulation
  y_sim <- euler_solve(y0, t_sim, rhs, params)

  # Clean trajectory at observation times
  y_obs_clean <- y_sim[obs_idx, , drop = FALSE]

  # Add noise
  peak_amp <- max(abs(y_obs_clean))
  sd_use   <- if (is.null(noise_sd)) 0.02 * peak_amp else noise_sd
  set.seed(seed)
  obs_data <- y_obs_clean +
    matrix(rnorm(length(obs_idx) * n_vars, 0, sd_use),
           length(obs_idx), n_vars)

  # Print parameter summary
  if (show_params) {
    cat("\n=== Data inspection ===\n")
    cat("Model parameters (true generating values):\n")
    for (nm in names(params)) {
      val <- params[[nm]]
      if (length(val) == 1) {
        cat(sprintf("  %-12s = %g\n", nm, val))
      } else {
        cat(sprintf("  %-12s = [%s]\n", nm,
                    paste(signif(val, 4), collapse = ", ")))
      }
    }
    cat(sprintf("\nNoise std. dev.: %.4g  (%.1f %% of peak amplitude)\n",
                sd_use, 100 * sd_use / peak_amp))
    cat(sprintf("Time grid    :  sim [%.3g, %.3g] step ~%.3g  |  obs step ~%.3g\n",
                min(t_sim), max(t_sim),
                mean(diff(t_sim)), mean(diff(t_obs))))
    cat(sprintf("Observations :  %d time points x %d state variable(s)\n\n",
                length(t_obs), n_vars))
  }

  # Plots: one per state variable
  plots <- lapply(seq_len(n_vars), function(i) {
    df_sim <- data.frame(t = t_sim, y = y_sim[, i], type = "Simulation")
    df_clean <- data.frame(t = t_obs, y = y_obs_clean[, i], type = "Clean obs")
    df_noisy <- data.frame(t = t_obs, y = obs_data[, i])

    ggplot() +
      # Full simulation trajectory
      geom_line(data = df_sim, aes(x = t, y = y),
                color = "gray60", linetype = "dashed", linewidth = 0.6) +
      # Clean trajectory at obs times
      geom_line(data = df_clean, aes(x = t, y = y),
                color = "steelblue", linewidth = 1) +
      # Noisy observations
      geom_point(data = df_noisy, aes(x = t, y = y),
                 color = "tomato", size = 1.5, alpha = 0.7) +
      labs(
        title    = var_names[i],
        subtitle = sprintf(
          "noise SD = %.3g  (%.1f %% of peak)",
          sd_use, 100 * sd_use / peak_amp
        ),
        x = "Time",
        y = "State"
      ) +
      theme_minimal() +
      theme(plot.subtitle = element_text(size = 9, color = "gray40"))
  })

  ncols <- min(n_vars, 3)
  do.call(
    grid.arrange,
    c(plots, list(
      ncol = ncols,
      top  = paste0(
        "Synthetic data  |  ",
        paste(names(params)[vapply(params, length, 1L) == 1],
              signif(unlist(params[vapply(params, length, 1L) == 1]), 3),
              sep = "=", collapse = "  ")
      )
    ))
  )

  invisible(list(y_sim = y_sim, y_obs_clean = y_obs_clean,
                 obs_data = obs_data))
}


# =============================================================================
# Example calls — uncomment to run
# =============================================================================

# --- Exponential decay ---
# inspect_data(ODE_CONFIGS$decay)

# --- Lotka-Volterra ---
# inspect_data(ODE_CONFIGS$lv)

# --- Sestak-Berggren (multi-temperature) ---
# inspect_data(ODE_CONFIGS$sb)

# --- Inspect with a custom noise level ---
# inspect_data(ODE_CONFIGS$lv, noise_sd = 2.0)

# --- Inspect with modified parameters without touching ODE_CONFIGS ---
# cfg_fast_decay <- ODE_CONFIGS$decay
# cfg_fast_decay$params$k <- 2.0
# inspect_data(cfg_fast_decay)
