# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, refactor/ode-model-interface]
  pull_request:

name: tests.yaml

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest

    container: rocker/tidyverse:latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: install2.r testthat reshape2 gridExtra

      - name: Run tests
        # This tells testthat to run all scripts inside the "tests" folder
        run: pwd && Rscript tests/testthat.R
